# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev123+gd6b46a1.d20230502'
__version_tuple__ = version_tuple = (0, 1, 'dev123', 'gd6b46a1.d20230502')
