# Auto-generated by /Users/tclo7153/git/workflows/nipype2pydra/nipype2pydra/package.py, do not edit as it will be overwritten

src_pkg_version = "1.10.0"
nipype2pydra_version = "0.5.1"
post_release = "1100051"
