from pydra.engine import specs
from pydra import ShellCommandTask
import typing as ty

input_fields = [
    (
        "ref_file",
        specs.File,
        {
            "argstr": "--ref={ref_file}",
            "help_string": "name of reference image",
            "mandatory": True,
        },
    ),
    (
        "in_file",
        specs.File,
        {
            "argstr": "--in={in_file}",
            "help_string": "name of input image",
            "mandatory": True,
        },
    ),
    (
        "affine_file",
        specs.File,
        {
            "argstr": "--aff={affine_file}",
            "help_string": "name of file containing affine transform",
        },
    ),
    (
        "inwarp_file",
        specs.File,
        {
            "argstr": "--inwarp={inwarp_file}",
            "help_string": "name of file containing initial non-linear warps",
        },
    ),
    (
        "in_intensitymap_file",
        list,
        {
            "argstr": "--intin={in_intensitymap_file}",
            "copyfile": False,
            "help_string": "name of file/files containing initial intensity mapping usually generated by previous fnirt run",
        },
    ),
    (
        "fieldcoeff_file",
        ty.Any,
        {
            "argstr": "--cout={fieldcoeff_file}",
            "help_string": "name of output file with field coefficients or true",
        },
    ),
    (
        "warped_file",
        str,
        {
            "argstr": "--iout={warped_file}",
            "help_string": "name of output image",
            "output_file_template": "{in_file}_warped",
        },
    ),
    (
        "field_file",
        ty.Any,
        {
            "argstr": "--fout={field_file}",
            "help_string": "name of output file with field or true",
        },
    ),
    (
        "jacobian_file",
        ty.Any,
        {
            "argstr": "--jout={jacobian_file}",
            "help_string": "name of file for writing out the Jacobian of the field (for diagnostic or VBM purposes)",
        },
    ),
    (
        "modulatedref_file",
        ty.Any,
        {
            "argstr": "--refout={modulatedref_file}",
            "help_string": "name of file for writing out intensity modulated --ref (for diagnostic purposes)",
        },
    ),
    (
        "out_intensitymap_file",
        ty.Any,
        {
            "argstr": "--intout={out_intensitymap_file}",
            "help_string": "name of files for writing information pertaining to intensity mapping",
        },
    ),
    (
        "log_file",
        str,
        {
            "argstr": "--logout={log_file}",
            "help_string": "Name of log-file",
            "output_file_template": "{in_file}_log.txt",
        },
    ),
    (
        "config_file",
        ty.Any,
        {
            "argstr": "--config={config_file}",
            "help_string": "Name of config file specifying command line arguments",
        },
    ),
    (
        "refmask_file",
        specs.File,
        {
            "argstr": "--refmask={refmask_file}",
            "help_string": "name of file with mask in reference space",
        },
    ),
    (
        "inmask_file",
        specs.File,
        {
            "argstr": "--inmask={inmask_file}",
            "help_string": "name of file with mask in input image space",
        },
    ),
    (
        "skip_refmask",
        bool,
        {
            "argstr": "--applyrefmask=0",
            "help_string": "Skip specified refmask if set, default false",
            "xor": ["apply_refmask"],
        },
    ),
    (
        "skip_inmask",
        bool,
        {
            "argstr": "--applyinmask=0",
            "help_string": "skip specified inmask if set, default false",
            "xor": ["apply_inmask"],
        },
    ),
    (
        "apply_refmask",
        list,
        {
            "argstr": "--applyrefmask={apply_refmask}",
            "help_string": "list of iterations to use reference mask on (1 to use, 0 to skip)",
            "sep": ",",
            "xor": ["skip_refmask"],
        },
    ),
    (
        "apply_inmask",
        list,
        {
            "argstr": "--applyinmask={apply_inmask}",
            "help_string": "list of iterations to use input mask on (1 to use, 0 to skip)",
            "sep": ",",
            "xor": ["skip_inmask"],
        },
    ),
    (
        "skip_implicit_ref_masking",
        bool,
        {
            "argstr": "--imprefm=0",
            "help_string": "skip implicit masking  based on value in --ref image. Default = 0",
        },
    ),
    (
        "skip_implicit_in_masking",
        bool,
        {
            "argstr": "--impinm=0",
            "help_string": "skip implicit masking  based on value in --in image. Default = 0",
        },
    ),
    (
        "refmask_val",
        float,
        {
            "argstr": "--imprefval={refmask_val}",
            "help_string": "Value to mask out in --ref image. Default =0.0",
        },
    ),
    (
        "inmask_val",
        float,
        {
            "argstr": "--impinval={inmask_val}",
            "help_string": "Value to mask out in --in image. Default =0.0",
        },
    ),
    (
        "max_nonlin_iter",
        list,
        {
            "argstr": "--miter={max_nonlin_iter}",
            "help_string": "Max # of non-linear iterations list, default [5, 5, 5, 5]",
            "sep": ",",
        },
    ),
    (
        "subsampling_scheme",
        list,
        {
            "argstr": "--subsamp={subsampling_scheme}",
            "help_string": "sub-sampling scheme, list, default [4, 2, 1, 1]",
            "sep": ",",
        },
    ),
    (
        "warp_resolution",
        ty.Any,
        {
            "argstr": "--warpres={warp_resolution},{warp_resolution},{warp_resolution}",
            "help_string": "(approximate) resolution (in mm) of warp basis in x-, y- and z-direction, default 10, 10, 10",
        },
    ),
    (
        "spline_order",
        int,
        {
            "argstr": "--splineorder={spline_order}",
            "help_string": "Order of spline, 2->Qadratic spline, 3->Cubic spline. Default=3",
        },
    ),
    (
        "in_fwhm",
        list,
        {
            "argstr": "--infwhm={in_fwhm}",
            "help_string": "FWHM (in mm) of gaussian smoothing kernel for input volume, default [6, 4, 2, 2]",
            "sep": ",",
        },
    ),
    (
        "ref_fwhm",
        list,
        {
            "argstr": "--reffwhm={ref_fwhm}",
            "help_string": "FWHM (in mm) of gaussian smoothing kernel for ref volume, default [4, 2, 0, 0]",
            "sep": ",",
        },
    ),
    (
        "regularization_model",
        ty.Any,
        {
            "argstr": "--regmod={regularization_model}",
            "help_string": "Model for regularisation of warp-field [membrane_energy bending_energy], default bending_energy",
        },
    ),
    (
        "regularization_lambda",
        list,
        {
            "argstr": "--lambda={regularization_lambda}",
            "help_string": "Weight of regularisation, default depending on --ssqlambda and --regmod switches. See user documetation.",
            "sep": ",",
        },
    ),
    (
        "skip_lambda_ssq",
        bool,
        {
            "argstr": "--ssqlambda=0",
            "help_string": "If true, lambda is not weighted by current ssq, default false",
        },
    ),
    (
        "jacobian_range",
        ty.Any,
        {
            "argstr": "--jacrange={jacobian_range},{jacobian_range}",
            "help_string": "Allowed range of Jacobian determinants, default 0.01, 100.0",
        },
    ),
    (
        "derive_from_ref",
        bool,
        {
            "argstr": "--refderiv",
            "help_string": "If true, ref image is used to calculate derivatives. Default false",
        },
    ),
    (
        "intensity_mapping_model",
        ty.Any,
        {
            "argstr": "--intmod={intensity_mapping_model}",
            "help_string": "Model for intensity-mapping",
        },
    ),
    (
        "intensity_mapping_order",
        int,
        {
            "argstr": "--intorder={intensity_mapping_order}",
            "help_string": "Order of poynomial for mapping intensities, default 5",
        },
    ),
    (
        "biasfield_resolution",
        ty.Any,
        {
            "argstr": "--biasres={biasfield_resolution},{biasfield_resolution},{biasfield_resolution}",
            "help_string": "Resolution (in mm) of bias-field modelling local intensities, default 50, 50, 50",
        },
    ),
    (
        "bias_regularization_lambda",
        float,
        {
            "argstr": "--biaslambda={bias_regularization_lambda}",
            "help_string": "Weight of regularisation for bias-field, default 10000",
        },
    ),
    (
        "skip_intensity_mapping",
        bool,
        {
            "argstr": "--estint=0",
            "help_string": "Skip estimate intensity-mapping default false",
            "xor": ["apply_intensity_mapping"],
        },
    ),
    (
        "apply_intensity_mapping",
        list,
        {
            "argstr": "--estint={apply_intensity_mapping}",
            "help_string": "List of subsampling levels to apply intensity mapping for (0 to skip, 1 to apply)",
            "sep": ",",
            "xor": ["skip_intensity_mapping"],
        },
    ),
    (
        "hessian_precision",
        ty.Any,
        {
            "argstr": "--numprec={hessian_precision}",
            "help_string": "Precision for representing Hessian, double or float. Default double",
        },
    ),
]
FNIRT_input_spec = specs.SpecInfo(
    name="Input", fields=input_fields, bases=(specs.ShellSpec,)
)

output_fields = [
    (
        "fieldcoeff_file",
        specs.File,
        {
            "help_string": "file with field coefficients",
            "requires": ["in_file"],
            "output_file_template": "{in_file}_fieldwarp",
        },
    ),
    (
        "field_file",
        specs.File,
        {
            "help_string": "file with warp field",
            "requires": ["in_file"],
            "output_file_template": "{in_file}_field",
        },
    ),
    (
        "jacobian_file",
        specs.File,
        {
            "help_string": "file containing Jacobian of the field",
            "requires": ["in_file"],
            "output_file_template": "{in_file}_field_jacobian",
        },
    ),
    (
        "modulatedref_file",
        specs.File,
        {
            "help_string": "file containing intensity modulated --ref",
            "requires": ["in_file"],
            "output_file_template": "{in_file}_modulated",
        },
    ),
]
FNIRT_output_spec = specs.SpecInfo(
    name="Output", fields=output_fields, bases=(specs.ShellOutSpec,)
)


class FNIRT(ShellCommandTask):
    input_spec = FNIRT_input_spec
    output_spec = FNIRT_output_spec
    executable = "fnirt"
